services:
  backend:
    # This now points to your correct Docker Hub repository.
    image: nikhilkolli1812/filesharing-backend:latest
    ports:
      - "8082:8082"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/file_storage_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    # This also points to the correct repository now.
    image: nikhilkolli1812/filesharing-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: file_storage_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

