# .github/workflows/main_ci.yml
name: Full-Stack CI/CD - v2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # SECURITY FIX: Use secrets here
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # Use secrets for security
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -f ./BackEnd/pom.xml clean install -DskipTests

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-backend:latest
          file: ./BackEnd/Dockerfile

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          # CORRECTED CONTEXT PATH
          context: ./FileSharingSystem_FrontEnd-main 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-frontend:latest
          # CORRECTED DOCKERFILE PATH
          file: ./FileSharingSystem_FrontEnd-main/Dockerfile

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Pull and run Docker Compose
        run: |
          # Use your server's shell to execute this.
          # Change the directory to where your docker-compose.yml is.
          cd /path/to/your/CIcdProject
          docker-compose pull
          docker-compose down
          docker-compose up -d