# .github/workflows/main_ci.yml
name: Full-Stack CI/CD - v2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: CIcdProject # Repository checked out into this folder

      # SECURITY FIX: Use secrets here
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # FIX 1: Update Maven path
      - name: Build with Maven
        run: mvn -f ./CIcdProject/BackEnd/pom.xml clean install -DskipTests

      # FIX 2: Update Backend context/file paths
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./CIcdProject/BackEnd 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-backend:latest
          file: ./CIcdProject/BackEnd/Dockerfile 

      # FIX 3: Update Frontend context/file paths (already done in your code)
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./CIcdProject/FileSharingSystem_FrontEnd-main
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-frontend:latest
          file: ./CIcdProject/FileSharingSystem_FrontEnd-main/Dockerfile

      # FIX 4: Update deploy paths for the self-hosted runner
    deploy:
        runs-on: self-hosted
        needs: build-and-push
        steps:
          - name: Pull and run Docker Compose
            run: |
              # The docker-compose file is now inside the CIcdProject folder
              cd /path/to/your/deployment_root/CIcdProject
              docker-compose pull
              docker-compose down
              docker-compose up -d