# .github/workflows/main_ci.yml
name: Full-Stack CI/CD - v2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        # Assumes BackEnd/pom.xml is at the root of the checked-out repo
        run: mvn -f ./BackEnd/pom.xml clean install -DskipTests

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          # Context for the backend folder
          context: ./BackEnd 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-backend:latest
          file: ./BackEnd/Dockerfile 

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          # Context for the renamed frontend folder
          context: ./FrontEnd 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-frontend:latest
          file: ./FrontEnd/Dockerfile # Dockerfile is inside the FrontEnd folder

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      # CRITICAL: Checkout code again to get the latest docker-compose.yml on the server
      - name: Checkout code on Server
        uses: actions/checkout@v3
        
      - name: Pull and run Docker Compose
        run: |
          # Change the directory to the root where BackEnd and FrontEnd sit
          # The entire repository is checked out into the runner's workspace root
          
          # The build names must match the service names in docker-compose.yml
          docker-compose pull
          docker-compose down
          docker-compose up -d