# .github/workflows/main_ci.yml
name: Full-Stack CI/CD - v2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Standard checkout, assumes BackEnd/ and FrontEnd/ are at repo root

      # --- Login Step (Must be here for security) ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # --- Build Backend ---
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        # Path for the pom.xml at repo root
        run: mvn -f ./BackEnd/pom.xml clean install -DskipTests

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./BackEnd 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-backend:latest
          file: ./BackEnd/Dockerfile # Explicitly set Dockerfile path
          
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./FrontEnd # Path to the clean folder name
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/filesharing-frontend:latest
          file: ./FrontEnd/Dockerfile # Path to the all-lowercase Dockerfile (for reliability)

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout code on Server
        uses: actions/checkout@v3
        
      - name: Pull and run Docker Compose
        run: |
          docker-compose pull
          docker-compose down
          docker-compose up -d